# Analisis Exploratorio de Metrobus

In [ ]:
import pandas as pd
import seaborn as sns

# Mostrar todas las columnas
pd.set_option("display.max_columns", None)

### Fase 1 — Exploración inicial del dataset (EDA)

In [2]:
# Cargamos los archivos CSV en los DataFrames

# Tablas de hechos
df_viajes = pd.read_csv("data/fact_viajes.csv")
df_incidencias = pd.read_csv("data/fact_incidencias.csv")
df_mantenimientos = pd.read_csv("data/fact_mantenimiento.csv")

# Tablas de dimensión
df_lineas = pd.read_csv("data/dim_linea.csv")
df_vehiculos = pd.read_csv("data/dim_vehiculo.csv")
df_conductores = pd.read_csv("data/dim_conductor.csv")
df_paradas = pd.read_csv("data/dim_parada.csv")
df_tarifas = pd.read_csv("data/dim_tarifa.csv")
df_cocheras = pd.read_csv("data/dim_depot.csv")

### Agregar todos los dataframes en un diccionario para poder hacer bucles con ellos y crear nuevos dataframes con la informacion unida en un solo dataframe

In [10]:
df_viajes.head(3)

,viaje_id,linea_id,vehiculo_id,conductor_id,parada_origen_id,parada_destino_id,fecha,anno,mes,dia_semana,es_festivo,franja_horaria,hora_salida_prog,hora_salida_real,hora_llegada_real,retraso_salida_min,duracion_real_min,pasajeros_subidos,ocupacion_pct,km_programados,km_recorridos,viaje_completado,consumo,tarifa_predominante_id
0,1,4,2,2,17,116,2023-08-14,2023,8,Monday,False,Tarde punta,17:50,18:09,19:22,19,73,78.0,0.609,14.1,14.1,True,4.69,4
1,2,4,3,3,5,48,2024-05-20,2024,5,Monday,False,Manana punta,07:10,07:23,08:30,13,67,115.0,0.885,14.1,14.1,True,5.86,2
2,3,5,4,4,33,110,2023-08-15,2023,8,Tuesday,False,Valle manana,12:30,12:30,13:05,0,35,47.0,0.362,7.3,7.3,True,3.15,3

In [12]:
df_viajes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   viaje_id                50000 non-null  int64
 1   linea_id                50000 non-null  int64
 2   vehiculo_id             50000 non-null  int64
 3   conductor_id            50000 non-null  int64
 4   parada_origen_id        50000 non-null  int64
 5   parada_destino_id       50000 non-null  int64
 6   fecha                   50000 non-null  object
 7   anno                    50000 non-null  int64
 8   mes                     50000 non-null  int64
 9   dia_semana              50000 non-null  object
 10  es_festivo              50000 non-null  bool
 11  franja_horaria          50000 non-null  object
 12  hora_salida_prog        50000 non-null  object
 13  hora_salida_real        50000 non-null  object
 14  hora_llegada_real       50000 non-null  object
 15  retraso_salida_min      50000 non-null  int64
 16  duracion_real_min       50000 non-null  int64
 17  pasajeros_subidos       49960 non-null  float64
 18  ocupacion_pct           50000 non-null  float64
 19  km_programados          50000 non-null  float64
 20  km_recorridos           50000 non-null  float64
 21  viaje_completado        50000 non-null  bool
 22  consumo                 48935 non-null  float64
 23  tarifa_predominante_id  50000 non-null  int64
dtypes: bool(2), float64(5), int64(11), object(6)
memory usage: 8.5+ MB

In [13]:
df_viajes.describe()

,viaje_id,linea_id,vehiculo_id,conductor_id,parada_origen_id,parada_destino_id,anno,mes,retraso_salida_min,duracion_real_min,pasajeros_subidos,ocupacion_pct,km_programados,km_recorridos,consumo,tarifa_predominante_id
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,49960.000000,50000.000000,50000.000000,50000.000000,48935.000000,50000.000000
mean,25000.500000,5.502600,21.496000,14.498800,20.547780,80.454760,2023.000380,6.518820,3.89218,62.600340,61.283907,0.455362,14.014620,13.910457,7.695104,3.606020
std,14433.901067,2.865665,12.120814,8.077258,11.562176,23.126044,0.816917,3.448467,6.76309,23.849155,36.847517,0.264251,4.949592,4.999930,6.221862,2.160808
min,1.000000,1.000000,1.000000,1.000000,1.000000,41.000000,2022.000000,1.000000,-99.00000,25.000000,1.000000,0.005000,7.300000,2.200000,0.550000,1.000000
25%,12500.750000,3.000000,11.000000,7.000000,11.000000,60.000000,2022.000000,4.000000,1.00000,44.000000,30.000000,0.227000,9.700000,9.700000,3.600000,2.000000
50%,25000.500000,6.000000,21.000000,14.000000,21.000000,80.500000,2023.000000,7.000000,2.00000,58.000000,56.000000,0.422000,12.600000,12.600000,5.340000,3.000000
75%,37500.250000,8.000000,32.000000,21.000000,31.000000,100.000000,2024.000000,10.000000,5.00000,78.000000,91.000000,0.688000,18.400000,18.400000,9.080000,5.000000
max,50000.000000,10.000000,42.000000,28.000000,40.000000,120.000000,2024.000000,12.000000,50.00000,129.000000,184.000000,0.995000,23.500000,23.500000,32.860000,9.000000

In [ ]:
df_viajes.describe()